version: "3.1"
services:
#######################################
# mariaDB
#######################################
  mariadb:
    image: mariadb:10.3
    restart: always
    environment:
      - MYSQL_DATABASE=demoDB
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=test
      - MYSQL_ROOT_PASSWORD=test
    volumes:
      - ./src:/www
    ports:
      - 3306:3306
#######################################
# phpmyadmin
#######################################
  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=demoDB
      - PMA_HOST=mariadb
      - PMA_PORT=3306
    ports:
      - 8080:80
    links:
      - mariadb

