name: React run build
run-name: Testing by ${{ github.actor }}
on:
  push:
    branches: [task-1]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Create Node environment
        uses: actions/setup-node@v1

      - name: Install dependencies
        run: npm install

      - name: Test build
        run: npm run build
